### ISSUE TITLE
复制网页上的图片并粘贴时会出现两个图片链接

### ISSUE THREAD

**Issue by Moyf** [vran-dev/obsidian-attachment-pro#3]
如图：
![image](https://github.com/vran-dev/obsidian-attachment-pro/assets/4013062/0983302f-c1bf-49b1-bedf-f4e104d31cf9)

断点发现在粘贴「网页上复制的图片」时，剪贴板包含两份数据：
![image](https://github.com/vran-dev/obsidian-attachment-pro/assets/4013062/ef5d91fd-3733-4c59-8fb4-6947b9a7d1a8)

都被处理了于是导致粘贴出来两份图片链接。

**Comment by vran-dev** [comment]
good job! thanks for your contribution
