### ISSUE TITLE
[BUG] 同时粘贴多张图片时会覆盖

### ISSUE THREAD

**Issue by Moyf** [vran-dev/obsidian-attachment-pro#7]
## 情况描述
我的自定义命名格式：
`${notename}-img-${now.toFormat('yyMMdd_HHmmss')}`

当复制3张图片然后粘贴进OB时，会只留下最后一张图片，前两张都被覆盖（因为时间是一致的）。
鉴于 uuid 太长了，还是只想用时间码，可否在**粘贴多个图片并且发现应用格式后命名重复**时，自动添加 -01、-02 的后缀？

## 情景举例
只有一张图片的时候：
![[240708_相机选购相关-img-240828_085704.jpeg]]

有多张图片的时候：
![[240708_相机选购相关-img-240828_085704.jpeg]]
![[240708_相机选购相关-img-240828_085704-01.jpeg]]
![[240708_相机选购相关-img-240828_085704-02.jpeg]]

> 就相当于操作系统的自动给重名文件添加后缀，避免冲突

**Comment by vran-dev** [comment]
fixed by @Moyf  at #8
